GDPR: Fix order anonymization for null addresses
Before, if an order of a contact that was about to be anonymized
had an order with a null shipping or billing address, it would result in the error:
`AttributeError: 'NoneType' object has no attribute '_meta'`,
when `Address.save()` was called.

Refs DO-190